const productos=[
    // Nike
    {
        id:"For-one",
        titulo:"For one",
        imagen:"https://boutiquesxpress.com/cdn/shop/products/tenis-nike-for-one-blanco-unisex15-calzado-elite-colombia-1259064175.jpg?v=1700805770",
        categoria:{
            nombre:"Nike",
            id:"Nike"
        },
        precio:120000
    },
    {
        id:"For-one-Bota",
        titulo:"For one Bota",
        imagen:"https://lasociedadelsneaker.com/wp-content/uploads/2024/02/force-bota-clasica-1.jpg",
        categoria:{
            nombre:"Nike",
            id:"Nike"
        },
        precio:150000
    },
        {
        id:"Nike-Shox",
        titulo:"Nike Shox",
        imagen:"https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/1857ae68-3339-48b7-baee-3e26bfcaddd6/NIKE+SHOX+TL.png",
        categoria:{
            nombre:"Nike",
            id:"Nike"
        },
        precio:130000
    },
        {
        id:"Air-Max",
        titulo:"Air Max",
        imagen:"https://i0.wp.com/shoopsneakers.com/wp-content/uploads/2024/07/NIKE-AIR-MAX-97-BLANCA-MORADA.jpg?fit=600%2C600&ssl=1",
        categoria:{
            nombre:"Nike",
            id:"Nike"
        },
        precio:180000
    },
// Jordan
    {
        id:"Jordan-3-Fragmen",
        titulo:"Jordan 3 Fragmen",
        imagen:"https://standshop.com.co/wp-content/uploads/2023/07/17cce708-2cb6-44ef-ac36-31858184d50a.jpg",
        categoria:{
            nombre:"Jordan",
            id:"Jordan"
        },
        precio:140000
    },
    {
        id:"Jordan-1-Charol-Negro",
        titulo:"Jordan 1 Charol Negro",
        imagen:"https://modozapatillas.com/upload/productos/galeria/normal/nike-air-jordan-1-mid-space-jam-d41380111f8558d2a5a9da7a095bbd0f.jpeg",
        categoria:{
            nombre:"Jordan",
            id:"Jordan"
        },
        precio:140000
    },
    {
        id:"Jordan-Dub-Zero",
        titulo:"Jordan Dub Zero",
        imagen:"https://static.wixstatic.com/media/1c2a53_0ce3112bb88c4dd98d0fb52d58f774ff~mv2.jpeg/v1/fit/w_500,h_500,q_90/file.jpg",
        categoria:{
            nombre:"Jordan",
            id:"Jordan"
        },
        precio:180000
    },
    {
        id:"Air-Jordan-4-Black",
        titulo:"Air Jordan 4 Black",
        imagen:"https://i.pinimg.com/736x/98/2c/84/982c8482d519f12f4b9468cdd9770f51.jpg",
        categoria:{
            nombre:"Jordan",
            id:"Jordan"
        },
        precio:130000
    },
    // Louis Vuitton
    {
        id:"Louis-Vuitton-Skate",
        titulo:"Louis Vuitton Skate",
        imagen:"https://www.workshopcol.co/cdn/shop/products/image00011_8e1f472f-3b3d-4861-a2bb-bc802357440b.jpg?v=1679258792&width=1946",
        categoria:{
            nombre:"Louis Vuitton",
            id:"Louis Vuitton"
        },
        precio:95000
    },
        {
        id:"Louis-Vuitton-Lv-Trainer",
        titulo:"Louis Vuitton Lv Trainer",
        imagen:"https://modozapatillas.com/upload/productos/galeria/normal/louis-vuitton-trainer-sneaker-low-modelo-106h-abdbdef318a29322170c2910307dd939.jpg",
        categoria:{
            nombre:"Louis Vuitton",
            id:"Louis Vuitton"
        },
        precio:100000
    },
        {
        id:"Luois-Vuitton-Brilho",
        titulo:"Luois Vuitton Brilho",
        imagen:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQX45-vkBFleZ4jTbxz6hsLirC8qxSxXFkNe_-OoKGcFdUxhayuJVX20K83geCzA7NfMKA&usqp=CAU",
        categoria:{
            nombre:"Louis Vuitton",
            id:"Louis Vuitton"
        },
        precio:150000
    },
        {
        id:"Louis-Vuitton-X-Nike",
        titulo:"Louis Vuitton X Nike",
        imagen:"https://media.vogue.es/photos/620bccfa65533ead332ac54d/2:3/w_2560%2Cc_limit/Louis%2520Vuitton%2520y%2520Nike%2520Air%2520Force%25201%2520por%2520Virgil%2520Abloh%2520%2520(1).jpg",
        categoria:{
            nombre:"Louis Vuitton",
            id:"Louis Vuitton"
        },
        precio:135000
    },
    //Chancletas
    {
        id:"Sharky-Chanclas",
        titulo:"Sharky Chanclas",
        imagen:"https://www.konnenservice.co/wp-content/uploads/2024/04/shanclas1.jpg",
        categoria:{
            nombre:"Chancletas",
            id:"Chancletas"
        },
        precio:105000
    },
    {
        id:"Yeezy-X-Adidas",
        titulo:"Yeezy X Adidas",
        imagen:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCGxHXTMStHT1exhi0lSiIv0AeX63uQPWiRQ&s",
        categoria:{
            nombre:"Chancletas",
            id:"Chancletas"
        },
        precio:100000
    },
    {
        id:"Nike-Victori-One-Slide-8",
        titulo:"Nike Victori One Slide 8",
        imagen:"https://down-cl.img.susercontent.com/file/cn-11134207-7qukw-lj74ps9fdrw6a5_tn.webp",
        categoria:{
            nombre:"Chancletas",
            id:"Chancletas"
        },
        precio:135000
    },
    {
        id:"Medusa-Kids",
        titulo:"Medusa Kids",
        imagen:"https://down-co.img.susercontent.com/file/sg-11134201-22120-b66h8k3oh3kve0",
        categoria:{
            nombre:"Chancletas",
            id:"Chancletas"
        },
        precio:150000
    },
    //Guayos
    {
        id:"Adidas-Predator",
        titulo:" Adidas Predator",
        imagen:"https://unitedstorecolombia.com/cdn/shop/products/33bb5d38.jpg?v=1679940521",
        categoria:{
            nombre:"Guayos",
            id:"Guayos"
        },
        precio:180000
    },
    {
        id:"Air-Zoom-Mercurial",
        titulo:"Air Zoom Mercurial",
        imagen:"https://unitedstorecolombia.com/cdn/shop/files/6FAA30D0-8D07-472B-8CD2-11780D6BFFAD.jpg?v=1727217520&width=1946",
        categoria:{
            nombre:"Guayos",
            id:"Guayos"
        },
        precio:150000
    },
    {
        id:"Nike-Phantom-GX-2",
        titulo:"Nike Phantom GX 2",
        imagen:"https://static.wixstatic.com/media/9622a0_6776a7a8a4974fed8a6b216891b3f9d4~mv2.webp/v1/fill/w_480,h_480,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/9622a0_6776a7a8a4974fed8a6b216891b3f9d4~mv2.webp",
        categoria:{
            nombre:"Guayos",
            id:"Guayos"
        },
        precio:120000
    },
    {
        id:"Adidas-F50-League",
        titulo:" Adidas F50 League",
        imagen:"https://prochampions.vtexassets.com/arquivos/ids/925025-800-800?v=638538199397870000&width=800&height=800&aspect=true",
        categoria:{
            nombre:"Guayos",
            id:"Guayos"
        },
        precio:130000
    },
];
const contenedorProductos = document.querySelector("#contenedor-productos");
const botonesCategorias = document.querySelectorAll(".boton-categoria");
const tituloPrincipal = document.querySelector("#titulo-principal");
let botonesAgregar = document.querySelectorAll(".producto-agregar");
const numerito = document.querySelector("#numerito");

function cargarProductos(productosElegidos) {

    contenedorProductos.innerHTML = "";

    productosElegidos.forEach(producto => {

        const div = document.createElement("div");
        div.classList.add("producto");
        div.innerHTML = `
            <img class="producto-imagen" src="${producto.imagen}" alt="${producto.titulo}">
            <div class="producto-detalles">
                <h3 class="producto-titulo">${producto.titulo}</h3>
                <p class="producto-precio">$${producto.precio}</p>
                <button class="producto-agregar" id="${producto.id}">Agregar</button>
            </div>
        `;

        contenedorProductos.append(div);
    })

    actualizarBotonesAgregar();
}

cargarProductos(productos);

botonesCategorias.forEach(boton => {
    boton.addEventListener("click", (e) => {

        botonesCategorias.forEach(boton => boton.classList.remove("active"));
        e.currentTarget.classList.add("active");

        if (e.currentTarget.id != "todos") {
            const productoCategoria = productos.find(producto => producto.categoria.id === e.currentTarget.id);
            tituloPrincipal.innerText = productoCategoria.categoria.nombre;
            const productosBoton = productos.filter(producto => producto.categoria.id === e.currentTarget.id);
            cargarProductos(productosBoton);
        } else {
            tituloPrincipal.innerText = "Todos los productos";
            cargarProductos(productos);
        }

    })
});

function actualizarBotonesAgregar() {
    botonesAgregar = document.querySelectorAll(".producto-agregar");

    botonesAgregar.forEach(boton => {
        boton.addEventListener("click", agregarAlCarrito);
    });
}

let productosEnCarrito;

let productosEnCarritoLS = localStorage.getItem("productos-en-carrito");

if (productosEnCarritoLS) {
    productosEnCarrito = JSON.parse(productosEnCarritoLS);
    actualizarNumerito();
} else {
    productosEnCarrito = [];
}

function agregarAlCarrito(e) {
    const idBoton = e.currentTarget.id;
    const productoAgregado = productos.find(producto => producto.id === idBoton);

    if(productosEnCarrito.some(producto => producto.id === idBoton)) {
        const index = productosEnCarrito.findIndex(producto => producto.id === idBoton);
        productosEnCarrito[index].cantidad++;
    } else {
        productoAgregado.cantidad = 1;
        productosEnCarrito.push(productoAgregado);
    }

    actualizarNumerito();

    localStorage.setItem("productos-en-carrito", JSON.stringify(productosEnCarrito));
}

function actualizarNumerito() {
    let nuevoNumerito = productosEnCarrito.reduce((acc, producto) => acc + producto.cantidad, 0);
    numerito.innerText = nuevoNumerito;
}

